### ISSUE TITLE
error when importing harden

### ISSUE THREAD

**Issue by warner** [agoric-labs/ses-adapter#1]
i don't have CI set up yet (I'm not sure this repo wants to be standalone; it might move into the SES-shim or agoric-sdk monorepo instead). But if you clone it and `yarn; yarn test`, you should see the following error:

```
~/stuff/agoric/ses-adapter$ yarn test
yarn run v1.22.0
$ tap --no-coverage --reporter specy test/**/test*.js
test/test-ses.js 2> /home/warner/stuff/agoric/ses-adapter/node_modules/@agoric/harden/dist/harden.cjs.js:1
test/test-ses.js 2> TypeError: RegExp.prototype.source getter called on non-RegExp object
test/test-ses.js 2>     at Object.get source [as source] (<anonymous>)
test/test-ses.js 2>     at Object.toString (<anonymous>)
test/test-ses.js 2>     at /home/warner/stuff/agoric/ses-adapter/node_modules/@agoric/harden/dist/harden.cjs.js:280:47
test/test-ses.js 2>     at Array.forEach (<anonymous>)
test/test-ses.js 2>     at getAnonIntrinsics (/home/warner/stuff/agoric/ses-adapter/node_modules/@agoric/harden/dist/harden.cjs.js:266:20)
test/test-ses.js 2>     at buildTable (/home/warner/stuff/agoric/ses-adapter/node_modules/@agoric/harden/dist/harden.cjs.js:1410:22)
test/test-ses.js 2>     at Object.<anonymous> (/home/warner/stuff/agoric/ses-adapter/node_modules/@agoric/harden/dist/harden.cjs.js:1430:22)
test/test-ses.js 2>     at Object.<anonymous> (/home/warner/stuff/agoric/ses-adapter/node_modules/@agoric/harden/dist/harden.cjs.js:1)
test/test-non-ses.js
  ✓ should be equal
  ✓ expect truthy value
  ✓ fooerror

test/test-ses.js


 FAIL  test/test-ses.js 139.027ms
  command: /home/warner/.nvm/versions/node/v13.7.0/bin/node
  args:
    - -r
    - /home/warner/stuff/agoric/ses-adapter/node_modules/esm/esm.js
    - test/test-ses.js
  exitCode: 1
  signal: null

Suites:   1 failed, 1 passed, 2 of 2 completed
Asserts:  1 failed, 3 passed, of 4
error Command failed with exit code 1.
```

This seems to happen when `SES-adapter` is imported after `lockdown()` is called. It smells like another error we've seen recently, but I'm forgetting the details.. was it an outdated version of `@agoric/harden` or `@agoric/make-hardener`?

@kriskowal @michaelfig does this ring any bells?

**Comment by warner** [comment]
I know we published a new version of `make-hardener`.. do we need to publish a new version of `harden` too?

**Comment by michaelfig** [comment]
Sorry, it doesn't ring any bells.

**Comment by michaelfig** [comment]
However, it seems to be a debug message that is `.toString`ing its argument at: https://github.com/Agoric/SES-shim/blob/master/packages/harden/src/anonIntrinsics.js#L143

(or equivalent in the old `harden` package.)

Change `${undeniable}` to `${name}` and it will throw with a different (hopefully more informative) error.

**Comment by kriskowal** [comment]
This looks like a new and exotic failure mode to me. There was another mode because `harden.prototype` is undefined in the latest version of make-hardener, which was available in the monorepo but not yet published.

**Comment by warner** [comment]
ah, yeah, that's what I was remembering

**Comment by warner** [comment]
This looks like the same error as https://github.com/Agoric/SES-shim/issues/230  , and both go away if I add `noTameRegExp: true` to the `lockdown()` arguments.
